#!/bin/bash
set -eou pipefail

pod_layer_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CYAN='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

command="${1:-}"

function error {
	msg="$(date '+%F %T') - ${BASH_SOURCE[0]}: line ${BASH_LINENO[0]}: ${command}: ${*}"
	>&2 echo -e "${RED}${msg}${NC}"
	exit 2
}

if [ -z "$pod_layer_dir" ]; then
	error "[error] enter the vars directory parameter"
fi

if [ ! -f "$pod_layer_dir/vars.sh" ]; then
	error "[error] there is no such file $pod_layer_dir/vars.sh"
fi

start="$(date '+%F %T')"
msg="[base-run] [$command] start ($pod_layer_dir)"
echo -e "${CYAN}$(date '+%F %T') ${msg}${NC}"

export var_pod_layer_dir="$pod_layer_dir"

# shellcheck disable=SC1090
. "${pod_layer_dir}/vars.sh"

tmp_load_file="$pod_layer_dir/vars.sh file"

if [ -n "${var_load_script_path:-}" ]; then
	# shellcheck disable=SC1090
	. "${pod_layer_dir}/${var_load_script_path}"
	tmp_load_file="${pod_layer_dir}/${var_load_script_path}"
fi

if [ -z "${var_pod_vars_dir:-}" ]; then
	error "[error] var_pod_vars_dir was not loaded from the file $tmp_load_file"
fi

if [ -z "${var_pod_script:-}" ]; then
	error "[error] var_pod_script was not loaded from the file $tmp_load_file"
fi

if [ ! -f "$var_pod_script" ]; then
	error "[error] main script file ($var_pod_script) not found"
fi

if [ -z "${var_pod_tmp_dir:-}" ]; then
	error "[error] var_pod_tmp_dir was not loaded from the file $tmp_load_file"
fi

if [ ! -d "$var_pod_tmp_dir" ]; then
	mkdir -p "$var_pod_tmp_dir"
fi

if [ -z "${var_pod_data_dir:-}" ]; then
	error "[error] var_pod_data_dir was not loaded from the file $tmp_load_file"
fi

if [ "$command" = '__skip__' ]; then
	echo "skipping..."
elif [ -n "${data_dir:-}" ]; then
	script_log_file_dir="$data_dir/log/main"

	if [ ! -d "$script_log_file_dir" ]; then
		[ -d "$data_dir" ] && [ "$(stat -c "%U" "$data_dir")" != "$(whoami)" ] \
			&& mkdircmd=( sudo mkdir ) \
			|| mkdircmd=( mkdir )

		"${mkdircmd[@]}" -p "${script_log_file_dir}"
	fi

	[ -d "$script_log_file_dir" ] && [ "$(stat -c "%U" "$script_log_file_dir")" != "$(whoami)" ] \
		&& cmdprefix=( sudo ) \
		|| cmdprefix=()

	teecmd=( ${cmdprefix+"${cmdprefix[@]}"} )
	teecmd+=( tee )

	log_file_tmp="${script_log_file_dir}/tmp.run.$(date '+%Y-%m-%d.%H-%M-%S').$$.log"

	{
		echo "#######################################################################"
		echo "$(date '+%F %T') [base-run] [$command] [log] start ($pod_layer_dir)"

		bash "${var_pod_script}" "${@}" && status=$? || status=$?

		if [[ $status -ne 0 ]]; then
			error "$command - exited with status $status"
		fi

		echo "$(date '+%F %T') [base-run] [$command] [log] end ($pod_layer_dir)"
		echo "#######################################################################"
	} 2>&1 | "${teecmd[@]}" --append "$log_file_tmp"

	log_file="${script_log_file_dir}/run.$(date '+%Y-%m-%d').log"

	catcmd=( ${cmdprefix+"${cmdprefix[@]}"} )
	catcmd+=( cat )

	"${catcmd[@]}" "$log_file_tmp" | "${teecmd[@]}" --append "$log_file" >/dev/null

	rmcmd=( ${cmdprefix+"${cmdprefix[@]}"} )
	rmcmd+=( rm )

	"${rmcmd[@]}" -f "$log_file_tmp"
else
	bash "${var_pod_script}" "${@}" && status=$? || status=$?

	if [[ $status -ne 0 ]]; then
		error "$command - exited with status $status"
	fi
fi

end="$(date '+%F %T')"
msg="[base-run] [$command] end ($pod_layer_dir)"
echo -e "${CYAN}$(date '+%F %T') ${msg}${NC}"

echo -e "${GREEN}[base-run] [$command] summary - $start to $end ${NC}"