#!/bin/bash
# shellcheck disable=SC1090
set -eou pipefail

arg_pod_vars_dir="$1"

CYAN='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

if [ -z "$arg_pod_vars_dir" ]; then
	msg="[error] enter the vars directory parameter"
	echo -e "${RED}$(date '+%F %T') ${msg}${NC}"
	exit 1
fi

shift;

if [ ! -f "$arg_pod_vars_dir/vars.sh" ]; then
	msg="[error] there is no such file $arg_pod_vars_dir/vars.sh"
	echo -e "${RED}$(date '+%F %T') ${msg}${NC}"
	exit 1
fi

start="$(date '+%F %T')"
msg="[run-env] [${1:-}] start ($arg_pod_vars_dir)"
echo -e "${CYAN}$(date '+%F %T') ${msg}${NC}"

. "${arg_pod_vars_dir}/vars.sh"

if [ -z "${var_main__pod_inner_dir:-}" ]; then
	msg="[error] var_main__pod_inner_dir not specified in the $arg_pod_vars_dir/vars.sh file"
	echo -e "${RED}$(date '+%F %T') ${msg}${NC}"
	exit 1
fi

if [ -z "${var_run__general__script_dir:-}" ]; then
	msg="[error] var_run__general__script_dir not specified in the $arg_pod_vars_dir/vars.sh file"
	echo -e "${RED}$(date '+%F %T') ${msg}${NC}"
	exit 1
fi

if [ -z "${var_run__general__script_env_file:-}" ]; then
	msg="[error] var_run__general__script_env_file not specified in the $arg_pod_vars_dir/vars.sh file"
	echo -e "${RED}$(date '+%F %T') ${msg}${NC}"
	exit 1
fi

pod_vars_full_dir="$(cd "$(dirname "$arg_pod_vars_dir")"; pwd -P)/$(basename "$arg_pod_vars_dir")"
pod_layer_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pod_full_dir="$pod_layer_dir/$var_main__pod_inner_dir"
pod_tmp_dir="$pod_layer_dir/tmp/$var_main__pod_inner_dir"
pod_script_env_file="$pod_layer_dir/$var_run__general__script_dir/$var_run__general__script_env_file"

if [ ! -d "$pod_full_dir" ]; then
	mkdir -p "$pod_full_dir"
fi

if [ ! -d "$pod_tmp_dir" ]; then
	mkdir -p "$pod_tmp_dir"
fi

export "POD_VARS_DIR=$pod_vars_full_dir"
export "POD_LAYER_DIR=$pod_layer_dir"
export "POD_FULL_DIR=$pod_full_dir"
export "POD_TMP_DIR=$pod_tmp_dir"
export "POD_SCRIPT_ENV_FILE=$pod_script_env_file"

"${pod_script_env_file}" "${@}"

end="$(date '+%F %T')"
msg="[run-env] [${1:-}] end ($arg_pod_vars_dir)"
echo -e "${CYAN}$(date '+%F %T') ${msg}${NC}"

echo -e "${GREEN}[run-env] [${1:-}] summary - $start to $end ${NC}"