#!/bin/bash
set -eou pipefail

pod_vars_dir="$1"

CYAN='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

if [ -z "$pod_vars_dir" ]; then
	msg="[error] enter the vars directory parameter"
	echo -e "${RED}$(date '+%F %X') ${msg}${NC}"
	exit 1
fi

shift;

if [ ! -f "$pod_vars_dir/vars.sh" ]; then
	msg="[error] there is no such file $pod_vars_dir/vars.sh"
	echo -e "${RED}$(date '+%F %X') ${msg}${NC}"
	exit 1
fi

start="$(date '+%F %X')"
msg="[run-env] [${1:-}] start ($pod_vars_dir)"
echo -e "${CYAN}$(date '+%F %X') ${msg}${NC}"

. "${pod_vars_dir}/vars.sh"

if [ -z "${pod_inner_dir:-}" ]; then
	msg="[error] pod_inner_dir not specified in the $pod_vars_dir/vars.sh file"
	echo -e "${RED}$(date '+%F %X') ${msg}${NC}"
	exit 1
fi

if [ -z "${scripts_dir:-}" ]; then
	msg="[error] scripts_dir not specified in the $pod_vars_dir/vars.sh file"
	echo -e "${RED}$(date '+%F %X') ${msg}${NC}"
	exit 1
fi

if [ -z "${script_env_file:-}" ]; then
	msg="[error] script_env_file not specified in the $pod_vars_dir/vars.sh file"
	echo -e "${RED}$(date '+%F %X') ${msg}${NC}"
	exit 1
fi

pod_vars_dir="$(cd "$(dirname "$pod_vars_dir")"; pwd -P)/$(basename "$pod_vars_dir")"
pod_layer_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pod_full_dir="$pod_layer_dir/$pod_inner_dir"
pod_script_env_file="$pod_layer_dir/$scripts_dir/$script_env_file"

export "POD_VARS_DIR=$pod_vars_dir"
export "POD_LAYER_DIR=$pod_layer_dir"
export "POD_FULL_DIR=$pod_full_dir"
export "POD_SCRIPT_ENV_FILE=$pod_script_env_file"

"${pod_script_env_file}" ${@}

end="$(date '+%F %X')"
msg="[run-env] [${1:-}] end ($pod_vars_dir)"
echo -e "${CYAN}$(date '+%F %X') ${msg}${NC}"

echo -e "${GREEN}[run-env] [${1:-}] summary - $start to $end ${NC}"